[package]
name = "rusty-gate"
version = "0.1.0"
authors = ["Shronk <ureshpohar@gmail.com>"]
edition = "2021"

[profile.dev]
opt-level = 3

[dev-dependencies]
shiba = { version = "0.1.1", default-features = false }

[dependencies]
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }
actix-web = "4.2.1"
serde = { version = "1.0.144", features = ["derive"] }
reqwest = { version = "0.11.11", features = ["json"] }
anyhow = { version = "1.0", default-features = false }
log = { version = "0.4.17", default-features = false }
structopt = { version = "0.3", default-features = false }
env_logger = "0.9.0"
